baseURL: https://yaubawebsite.netlify.app
languageCode: en-us
title: Bakouan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     This is Youbson portfolio website
    title: Hi, my name is Bakouan
  blog: {}
  contact:
    address:
      - city: Koudougou
        country: Burkina Faso
        street: Rue 14
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ybakouan65@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (00226) 65 82 98 07 / 65 89 65 49 / 71 30 22 16
        title: Phone
  custom_css: []
  custom_js: []
  description: I'm Bakouan Youba, I have 22. I'm a student in IT domain at BIT/koudougou/Burkina Faso
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Youbson Group
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/bakouanYouba
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/youba.bakouan.73
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Y0uBs0N
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/youba-bakouan-8a2829189
  image: ''
  name: Bakouan Youba
  navigation:
    button1:
      - name: Go Now
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Go Now
    enable: yes
    subtitle: "This is my entertainment website. I invite you to visit it and contact me if any need"
    title: Massa libero
    url: blogs
